### PR TITLE
Typed Ember object model

### PR DESCRIPTION
**Pull request by dwickern**
- object model
  - [x] create
  - [x] extend
  - [x] reopen/reopenClass
  - [x] mixins
- computed properties
  - [x] typed `Ember.computed(...)`
  - [x] get/set
  - [x] getProperties/setProperties

### CODE REVIEW

**Comment by dwickern** [comment]
I've tried to find the right balance between type safety and usability. The strongest/most correct typings will create lots of boilerplate and ceremony. If the typings are too weak, you might as well write javascript.

There are a few things that are impossible to type, or not worth it due to the added boilerplate. I'm going to open a few issues here to track typescript features which could help us type things more accurately.

**Comment by chriskrycho** [comment]
Awesome. I will pull this down and try it out in our app on Monday and report any issues I run into. I'll also take a close look at the definitions and leave questions or comments then. Thank you again for all your work on this!

**Comment by dwickern** [comment]
Wonderful! I added instructions to the readme. FYI I think you need `noImplicitAny` and `noImplicitThis` for the typings to work.

**Comment by chriskrycho** [comment]
All right, I expect this to be a bit of work 😬 but @dwickern now that we've landed the previous two Pos, can you (a) rebase and then (b) pull in @vlascik's as you had taken a stab at previously to support the new modules API?

**Comment by dwickern** [comment]
Strange test failure, it looks like some state is shared with #10 on the CI server
```
/home/travis/build/typed-ember/ember-typings/types/ember/ember-tests.ts
ERROR: 3:10  expect  TypeScript compile error: Module ''@ember/object/computed'' has no exported member 'or'.
```

**Comment by chriskrycho** [comment]
Restarting that build. That's weird.

**Comment by chriskrycho** [comment]
This looks awesome. I'm going to pull it down and use it locally starting this afternoon, will report if I run into any pain points or problems.

**Comment by chriskrycho** [comment]
Yeeeeeeees! :clap:

**Pull request merged**
