### PR TITLE
Add missing public typings

### PR DESCRIPTION
**Pull request by vlascik**
This adds all missing public exports needed for new modules api (rfc 176) imports. 
Warning: contains duplicates of Ember.computed typings done also in https://github.com/typed-ember/ember-typings/pull/3
some are better in that PR, some might be better here, so they might need to be checked on case by case basis.
Along with https://gist.github.com/vlascik/bd1843403610f98c9550bb635a6501d9 this should be enough to get the new imports working.

### CODE REVIEW

**Comment by chriskrycho** [comment]
Thanks for adding these! I'll defer to @dwickern on the sequence he wants to use in terms of merging things and integrating with his own in-progress PR (as I am with #3). That said, it seems like we might be able to do this iteratively, so open for conversation:

1. Land #3 and #4.

2. Update the typings to use the format @dwickern discovered to work for the ambient typings and having the namespaced `@ember/...` versions in the same file, i.e. like so:

    ```typescript
    declare module 'ember' {
        import Rsvp from 'rsvp';

        namespace Ember {
            // ...
            class Component {}
            // ...
        }

        export default Ember;
    }

    declare module '@ember/component' {
        import Ember from 'ember';
        export default Ember.Component;
    }
    ```

3. Upstream those changes to Definitely Typed.

4. Rebase the new, more helpful type definitions (#1) onto those and see if we can land *that* in the next week or two.

Thoughts? @csantero would welcome your input as well given #3.

**Comment by vlascik** [comment]
Sounds good to me, after #3 and #4 are merged I will create a PR for step 2.

**Comment by chriskrycho** [comment]
@vlascik can you merge (I'd prefer that, not rebase, so the history is clear) the latest changes from merging #3? I'll merge this after that.

**Comment by chriskrycho** [comment]
@vlascik thanks, looks 98% awesome! It looks like you've got a BOM (byte-order mark if you haven't bumped into that before) on the file which is causing the test to fail (see [here](https://travis-ci.org/typed-ember/ember-typings/builds/264654576#L537).

You might also check for a setting in whatever editor you're using to make sure it's *not* putting BOMs on things. Thanks!

**Comment by vlascik** [comment]
yep, I saw it, sorry, I was trying new merge tool, apparently it adds BOM by default, I got distracted by other things. I will fix it now.

**Comment by vlascik** [comment]
So I think I'm done, one thing though, there are now some typings for engines classes, and those were added in Ember 2.8. Should I change file header where it says Ember 2.7 as well?

**Comment by chriskrycho** [comment]
Yeah, go ahead and bump that as well. We're going to need to hammer out at some point which version we consider ourselves as being in sync with, but I haven't had a chance to think that through all the way yet.

**Comment by chriskrycho** [comment]
Once you have the 2.8 bit pushed, I'll wait for the tests to pass then merge. Thanks!

**Pull request merged**
