### PR TITLE
Fix Object.extend not including static properties

### PR DESCRIPTION
**Pull request by dwickern**
This makes static properties and methods work when using `.extend()`:
```ts
class Component extends Object {
  static positionalParams: string | string[];
}
Component.positionalParams; // good

class Component2 extends Component {}
Component2.positionalParams; // good

const Component3 = Component.extend();
Component3.positionalParams; // error
```

### CODE REVIEW

**Comment by dwickern** [comment]
/cc @dfreeman 

I had to do some strange things to make this work. Could you have a look?

**Comment by dfreeman** [comment]
I'll take a look and see what I can come up with.

**Comment by dfreeman** [comment]
I see, so it's basically capturing all the properties on the base class but throwing away the fact that it's constructible so that its own `new () ...` doesn't conflict with that of the child class? Clever.

I'm a bit confused as to why the compiler requires [this line](https://github.com/typed-ember/ember-typings/pull/29/files#diff-49f99cfcf81b26a8c52a0257f0bb0827R284) to consider `EmberClassConstructor<T>` a "constructor function type" when that signature is already implied by the line below, but if it works... ¯\\\_(ツ)_/¯

**Comment by dwickern** [comment]
Since the statics are inherited now from `CoreObject`, I thought we could get rid of the duplicate definitions of `create`, `createWithMixins`, `reopen`, etc. I haven't been able to make it work though

**Comment by dfreeman** [comment]
Just opened a PR against this branch to get rid of the duplicate definitions—the only issue I saw was `Reopen` and `Detect` not properly capturing statics.

**Comment by dwickern** [comment]
When I was playing around on this branch from another project, I had build errors extending from our classes:

> lib/-private/build-time-component.ts(3,1): error TS4082: Default export of the module has or is using private name 'EmberClassConstructor'.
lib/-private/build-time-component.ts(3,1): error TS4082: Default export of the module has or is using private name 'Function'.
lib/-private/build-time-component.ts(3,1): error TS4082: Default export of the module has or is using private name 'Objectify'.

It turns out this code
```ts
import Ember from 'ember';

export default Ember.CoreObject.extend({
  tagName: 'div',

  toNode() {
    return undefined;
  }
});
```

Gets compiled to this definition
```ts
import Ember from 'ember';
declare const _default: Ember.Objectify<typeof Ember.CoreObject> & Ember.EmberClassConstructor<{
    tagName: string;
    toNode(): undefined;
} & Ember.CoreObject>;
export default _default;
```

Consequently `Objectify` and `EmberClassConstructor` need to be public API. I'm not sure what the best practice is. Do we export them from the Ember namespace like I've done here?

**Comment by dfreeman** [comment]
It would be great if we could just get rid of those types completely instead of having to export invented concepts.

I believe `Objectify<T>` is equivalent to `Pick<T, keyof T>`, and if we add `constructor(...args: any[])` to `CoreObject`, then we could drop `EmberClassConstructor<T>` completely in favor of `new () => T`.

Making those two changes locally, the test suite still passes. Thoughts?

**Comment by dwickern** [comment]
Using the `Pick<>` definition, the class from before compiles to
```ts
import Ember from 'ember';
declare const _default: Pick<typeof Ember.CoreObject, "prototype" | "create" | "createWithMixins" | "extend" | "reopen" | "reopenClass" | "detect" | "detectInstance" | "eachComputedProperty" | "metaForProperty" | "isClass" | "isMethod"> & (new () => {
    tagName: string;
    toNode(): undefined;
} & Ember.CoreObject);
export default _default;
```

So I thought, what if I just inline the type mapping as `=> { [P in keyof Statics]: Statics[P] } & { ... }`. Here's what I get
```ts
import Ember from 'ember';
declare const _default: {
    prototype: Ember.CoreObject;
    create: <Instance, Extensions extends Partial<Instance> & {
        [key: string]: any;
    }>(this: new () => Instance, args?: (Extensions & ThisType<Extensions & Instance>) | undefined) => Extensions & Instance;
    createWithMixins: <Instance extends M1Base, M1, M1Base, Extensions extends Partial<Instance> & {
        [key: string]: any;
    }>(this: new () => Instance, mixin1: M1 | Ember.Mixin<M1, M1Base>, args?: (Extensions & ThisType<Extensions & Instance & M1>) | undefined) => Extensions & Instance & M1;
    extend: {
        <Statics, Instance>(this: Statics & (new () => Instance)): {
            [K in keyof Statics]: Statics[K];
        } & (new () => Instance);
        <Statics, Instance extends B1, T1 extends Partial<Instance> & {
            [key: string]: any;
        }, B1>(this: Statics & (new () => Instance), arg1: (T1 & ThisType<Instance & T1>) | (Ember.Mixin<T1, B1> & ThisType<Instance & T1>)): any & (new () => T1 & Instance);
        <Statics, Instance extends B1 & B2, T1 extends Partial<Instance> & {
            [key: string]: any;
        }, B1, T2 extends Partial<Instance> & {
            [key: string]: any;
        }, B2>(this: Statics & (new () => Instance), arg1: (T1 & ThisType<Instance & T1>) | (Ember.Mixin<T1, B1> & ThisType<Instance & T1>), arg2: (T2 & ThisType<Instance & T1 & T2>) | (Ember.Mixin<T2, B2> & ThisType<Instance & T1 & T2>)): Pick<Statics, keyof Statics> & (new () => T1 & T2 & Instance);
        <Statics, Instance extends B1 & B2 & B3, T1 extends Partial<Instance> & {
            [key: string]: any;
        }, B1, T2 extends Partial<Instance> & {
            [key: string]: any;
        }, B2, T3 extends Partial<Instance> & {
            [key: string]: any;
        }, B3>(this: Statics & (new () => Instance), arg1: (T1 & ThisType<Instance & T1>) | (Ember.Mixin<T1, B1> & ThisType<Instance & T1>), arg2: (T2 & ThisType<Instance & T1 & T2>) | (Ember.Mixin<T2, B2> & ThisType<Instance & T1 & T2>), arg3: (T3 & ThisType<Instance & T1 & T2 & T3>) | (Ember.Mixin<T3, B3> & ThisType<Instance & T1 & T2 & T3>)): Pick<Statics, keyof Statics> & (new () => T1 & T2 & T3 & Instance);
        <Statics, Instance extends B1 & B2 & B3 & B4, T1 extends Partial<Instance> & {
            [key: string]: any;
        }, B1, T2 extends Partial<Instance> & {
            [key: string]: any;
        }, B2, T3 extends Partial<Instance> & {
            [key: string]: any;
        }, B3, T4 extends Partial<Instance> & {
            [key: string]: any;
        }, B4>(this: Statics & (new () => Instance), arg1: (T1 & ThisType<Instance & T1>) | (Ember.Mixin<T1, B1> & ThisType<Instance & T1>), arg2: (T2 & ThisType<Instance & T1 & T2>) | (Ember.Mixin<T2, B2> & ThisType<Instance & T1 & T2>), arg3: (T3 & ThisType<Instance & T1 & T2 & T3>) | (Ember.Mixin<T3, B3> & ThisType<Instance & T1 & T2 & T3>), arg4: (T4 & ThisType<Instance & T1 & T2 & T3 & T4>) | (Ember.Mixin<T4, B4> & ThisType<Instance & T1 & T2 & T3 & T4>)): Pick<Statics, keyof Statics> & (new () => T1 & T2 & T3 & T4 & Instance);
    };
    reopen: <Statics, Instance, Extra extends Partial<Instance> & {
        [key: string]: any;
    }>(this: Statics & (new () => Instance), args?: (Extra & ThisType<Instance & Extra>) | undefined) => Pick<Statics, keyof Statics> & (new () => Instance & Extra);
    reopenClass: <Class, Extra extends Partial<Class> & {
        [key: string]: any;
    }>(this: Class, args?: Extra | undefined) => Class & Extra;
    detect: <Statics, Instance>(this: Statics & (new () => Instance), obj: any) => obj is Pick<Statics, keyof Statics> & (new () => Instance);
    detectInstance: <Instance>(this: new () => Instance, obj: any) => obj is Instance;
    eachComputedProperty: (callback: Function, binding: {}) => void;
    metaForProperty: (key: string) => {};
    isClass: boolean;
    isMethod: boolean;
} & (new () => {
    tagName: string;
    toNode(): undefined;
} & Ember.CoreObject);
export default _default;

```

**Comment by dfreeman** [comment]
Just to confirm I'm not missing something, those two snippets are semantically equivalent, right?

My one concern now that I'm thinking about it (which impacts both, though more so in the inline version) is that the declaration is capturing the extended class's static interface 'by value' rather than 'by reference', if that makes sense.

Suppose I'm an addon author publishing my code with a `.d.ts` file generated like this against `@types/ember@x.y.z`, and a consumer is using my addon with `@types/ember@x.a.b`, where there have been tweaks to the signatures of some static methods in core Ember classes. Is that likely to cause a problem?

**Comment by dwickern** [comment]
I believe they're all equivalent structural types.

I have the same compatibility concerns. If an addon publishes that inlined type, it might conflict with another version of the ember typings.

I think the ideal solution would reference `Ember.CoreObject` but none of its implementation details, and ideally not expose imaginary types like `EmberClassConstructor`.

```
```
```
import Ember from 'ember';
declare const _default: Readonly<typeof Ember.CoreObject> & (new () => {
    tagName: string;
    toNode(): undefined;
} & Ember.CoreObject);
export default _default;

```

**Comment by dwickern** [comment]
If we want to allow multiple arguments to constructors like before we will need a `new()` overload
```ts
static extend<Statics, Instance extends B1,
    T1 extends EmberClassArguments<Instance>, B1>(
    this: Statics & (new () => Instance),
    arg1: MixinOrLiteral<T1, B1> & ThisType<Instance & T1>
): Readonly<Statics> & {
    new (): T1 & Instance;
    new (...args: any[]): T1 & Instance
};
```

**Comment by dfreeman** [comment]
> I think the ideal solution would reference Ember.CoreObject but none of its implementation details, and ideally not expose imaginary types like EmberClassConstructor.

Agreed on both counts! I like `Readonly` as an improvement over `Pick`.

> If we want to allow multiple arguments to constructors like before we will need a new() overload

Ah right, subclasses wouldn't inherit `new(...params: any[])` from `CoreObect` because we're going out of our way not to capture the constructor 😄. The verbosity of the `new()` overload feels a little unfortunate, but seems like the best path forward IMO.

**Comment by dwickern** [comment]
Unfortunately it does create some duplication
```ts
import Ember from 'ember';
declare const _default: Readonly<typeof Ember.CoreObject> & {
    new (): {
        tagName: string;
        readonly classNames: any[];
        toNode(): undefined;
    } & Ember.CoreObject;
    new (...args: any[]): {
        tagName: string;
        readonly classNames: any[];
        toNode(): undefined;
    } & Ember.CoreObject;
};
export default _default;
```

**Comment by dwickern** [comment]
That latest commit generates the right code. I'm not sure that automated tests are possible. You'd think typescript would stop you from defining broken types.

**Comment by dfreeman** [comment]
👍  the explanatory comments are a nice add, too!

Agreed it seems odd that TS would allow for broken exports, but I'm not sure what we can do about it short of just smoke testing against other apps by hand.

**Pull request merged**
