### PR TITLE
Add typings for ember-inflector

### PR DESCRIPTION
**Pull request by dwickern**
Then we can pull it out from ember-data

### CODE REVIEW

**Comment by dwickern** [comment]
@chriskrycho I just noticed you have a PR at emberjs/ember-inflector#132

**Comment by chriskrycho** [comment]
Yeah, though I think it's been lost. Two notes:

1. I don't know what all is desired to be treated as public API for Inflector. cc. @locks @rwjblue on that.
2. It seems iffy to me whether we should merge those bits into the ember namespace. Obviously that represents what's actually happening, so perhaps we should do it to support good backwards compatibility—but on the other hand we have a good opportunity here to push more toward the new modules API, and per the last core team meeting notes, they really want TS stuff that gets into Ember.js itself *only* to support the modules API.

**Comment by dwickern** [comment]
The tests were pulled from official guides and docs so I consider those to be public API. I might have grabbed some private Inflector methods though

I would like to support backwards compatibility to a reasonable extent. If we want to remove public APIs it should go through the official deprecation process and the typings will follow suit. It's going to be hard enough to convert a project from JS to TS _without_ API changes.

**Comment by chriskrycho** [comment]
That seems like a reasonable stance to me.

**Comment by dwickern** [comment]
The next step is to pull these inflector APIs out of the ember-data typings.

**Pull request merged**
