### PR TITLE
ember-decorators: add the named 'action' export

### PR DESCRIPTION
**Pull request by bartocc**

### CODE REVIEW

**Comment by chriskrycho** [comment]
@bartocc looks great! Can you add a simple test for it to the existing tests? We're aiming to have good coverage of the various pieces, both as a model for the rest of the typing ecosystem and to prevent regressions. I'd just update the existing tests roughly like so. In the imports—

```diff
- import { action, computed } from 'ember-decorators/object';
+ import { action, computed } from 'ember-decorators/object';
```

and in the body of the `UserComponent` definition—

```diff
class UserComponent extends Ember.Component {

+  @action
+  handleSomeAction() {}
```

**Comment by bartocc** [comment]
Sure, I completely forgot about the test.

If you find a way to make the tests pass with `@action` and not `@action()` that'd be great.
I got stuck with the TS1241 error.

**Comment by chriskrycho** [comment]
Thanks for adding the test! I *suspect* for just having `@action`, we'll need to wait for TS 2.6 or later, sadly: the latest version of the decorator proposal is still just in the [Future](https://github.com/Microsoft/TypeScript/wiki/Roadmap#future) section of their roadmap. :sigh:

**Comment by dwickern** [comment]
Thanks @bartocc !

**Pull request merged**
