### PR TITLE
Implement typed computed property access

### PR DESCRIPTION
**Pull request by dwickern**
So that `obj.computedProperty` correctly returns an `Ember.ComputedProperty` and `obj.get('computedProperty')` returns the actual property type

### CODE REVIEW

**Comment by dwickern** [comment]
I'm not sure why the `Fix<T>` mapped type is needed, but it is-- try redefining as `type Fix<T> = T` and `ComputedProperties<T>` will no longer work

Any idea why this would happen @dfreeman @NaridaL ?

**Comment by dfreeman** [comment]
This looks like it could be a compiler bug? Defining `type Fix<T> = T` and then playing with this code:

```ts
Ember.Object.extend({
    field: 'hello',
    method() {
        this.get('isDestroyed');
        this.get('field');
    }
});
```

I see `argument of type '"field"' is not assignable to parameter of type '"_super" | "init" | ...` annotated on `this.get('field')`.

However, if I swap the intersection order `ThisType` argument for `extend` on line 670 so that it reads `T1 & Instance` instead of `Instance & T1`, I instead see `argument of type '"isDestroyed"' is not assignable to parameter of type '"field" | "method"'.`

My best guess is that `Fix<A & B>` is "flattening" the intersection type to work around this bug.

**Comment by dwickern** [comment]
I agree this does seem like a compiler bug. It's strange that merging `T & U` would evaluate to `T` and completely discard `U`. I wasn't able to find an open issue about it.

@DanielRosenwasser Could you take a look at this? If you think it's a bug then we could try to come up with a minimal reproduction

**Comment by dwickern** [comment]
Nice! Here's a [with the workaround](http://www.typescriptlang.org/play/index.html#src=declare%20function%20get%3CT%2C%20Key%20extends%20keyof%20T%20%3D%20keyof%20T%3E(obj%3A%20%7B%5BK%20in%20keyof%20T%5D%3A%20T%5BK%5D%7D%2C%20key%3A%20Key)%3A%20T%5BKey%5D%3B%0D%0A%0D%0Adeclare%20const%20obj%3A%20%7B%20flag%3A%20boolean%20%7D%20%26%20%7B%20field%3A%20string%20%7D%3B%0D%0A%0D%0Aget(obj%2C%20%27flag%27)%3B%0D%0Aget(obj%2C%20%27field%27)%3B%0D%0A%0D%0Atype%20Fix%3CT%3E%20%3D%20%7B%5BP%20in%20keyof%20T%5D%3A%20T%5BP%5D%7D%0D%0A%0D%0Adeclare%20const%20obj2%3A%20Fix%3C%7B%20flag%3A%20boolean%20%7D%20%26%20%7B%20field%3A%20string%20%7D%3E%3B%0D%0A%0D%0Aget(obj2%2C%20%27flag%27)%3B%0D%0Aget(obj2%2C%20%27field%27)%3B%0D%0A)

**Comment by DanielRosenwasser** [comment]
Sorry for the delay; the workaround works because the mapped type is just running through and plucking each constituent type's properties and adding them to a single object type. Anders should have a fix up.

**Pull request merged**
