### PR TITLE
Fix being unable to reference Ember.RSVP.Promise as a type

### LINKED ISSUE #6: Missing re-export for Rsvp
tsc throws an exception for references to Ember.RSVP.Promise:`"TS2694: Namespace 'Ember' has no exported member 'RSVP'"`. This worked in a previous version of @types/ember.
An example of a typing that fails is:
`(urn: string): Ember.RSVP.Promise<IMetric, any>`

Thanks

### PR DESCRIPTION
**Pull request by dwickern**
Fixes #6

### CODE REVIEW

**Comment by chriskrycho** [comment]
**Discussion:** should we fix this for the sake of backwards compatibility, or just strongly recommend users switch? There's a *lot* to backfill if we backfill. And maybe that's the right thing to do. However, since it's as simple as `import RSVP from 'rsvp'` and replacing `Ember.RSVP` with `RSVP` or dropping any destructuring from the `Ember` object…

My current thought is, begrudgingly, we should backfill unless/until the `Ember.RSVP` version is deprecated. (Which I'd like to see it be shortly, and may even write the RFC to that effect if I get a chance in the next few weeks and no one else beats me to it.) 🤔

**Comment by dwickern** [comment]
> There's a lot to backfill if we backfill

Is there? I think only this one type alias is needed.

**Comment by chriskrycho** [comment]
Ah, I think you're right. That's *weird* that it doesn't re-export all members.

**Comment by dwickern** [comment]
Yeah I don't get it. There's something about types and values being separate. I have the same problem in #1:
```js
const MyClass = Ember.Object.extend();
const myClass: MyClass; // error
const myClass: typeof MyClass.prototype; // valid, but isn't this a roundabout way of saying the above line?
```
At least it works with ES6 classes:
```js
class MyClass extends Ember.Object {}
const myClass: MyClass; // valid
```

**Pull request merged**
